services:
  - type: web
    name: wokilite-api
    runtime: node
    plan: free
    buildCommand: cd api && npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: cd api && npm start
    envVars:
      - key: DATABASE_URL
        value: file:./prod.db
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000